apiVersion: v1
kind: Service
metadata:
  name: main-api
  namespace: k-challenge-namespace
  labels:
    app: main-api
    environment: dev
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: main-api

