apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: k-challenge-namespace

resources:
  - namespace.yaml
  - service-account.yaml

# Labels are defined directly in the resource files
# (commonLabels can be used here since these resources don't have immutable selectors)

