apiVersion: v1
kind: ServiceAccount
metadata:
  name: k-challenge-app-sa
  namespace: k-challenge-namespace
  labels:
    app: k-challenge
    environment: dev
---
# Note: For EKS with IRSA, you would add this annotation:
# annotations:
#   eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/k-challenge-dev-kubernetes-service-account-role
#
# For local Kubernetes (minikube/kind), AWS credentials are provided via Secret
# See aws-credentials-secret.yaml

