apiVersion: v1
kind: Service
metadata:
  name: auxiliary-service
  namespace: k-challenge-namespace
  labels:
    app: auxiliary-service
    environment: dev
spec:
  type: ClusterIP
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
    name: http
  selector:
    app: auxiliary-service

